### ISSUE TITLE
Supporting new devices

### ISSUE THREAD

**Issue by manuchis** [madchicken/homebridge-zigbee-nt#2]
Hi! thanks for mantaining the plugin and keep updating. 

I've forked your project to add new devices. I would like to learn how to do it so I don't have to disturb you (if sucessful we can do some merge). However I failed on my adventure in creating new accesory with a Gledopto device. 
I've updated the accessories folder making use of Ikea bulb dimmer which has the same properties of Gledopto dimmer, and also the 'index.ts' to support the device. I also checked that it is supported by herdmans' controllers and it is all right. It was paired successfully but accesory doesn't appears. 

The Zigbee.db says: 
`{"id":11,"type":"Router","ieeeAddr":"0x00124b001f79d7f0","nwkAddr":44526,"manufId":0,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-C-009","epList":[11,13],"endpoints":{"11":{"profId":49246,"epId":11,"devId":256,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"GL-C-009","manufacturerName":"GLEDOPTO","powerSource":1,"zclVersion":1,"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20131206","swBuildId":"1.0.8"}}},"binds":[]},"13":{"profId":49246,"epId":13,"devId":256,"inClusterList":[4096],"outClusterList":[4096],"clusters":{},"binds":[]}},"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20131206","swBuildId":"1.0.8","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1593706063667}`

And the log: 
`[37m[7/2/2020, 22:11:25] [39m[36m[ZigBee Hub] [39mUnrecognized device: 0x00124b001f79d7f0 GLEDOPTO GL-C-009
`
The fork can be found [here](https://github.com/manuchis/homebridge-zigbee-nt/tree/gledopto)
Please let me know if I'm missing something, it would be great to learn how to do it right. 

Bests,

**Comment by madchicken** [comment]
Hi! I'm super happy to see interest around this plugin. Two things here:

- Please, take a look to my last update (v1.0.0-rc.1), I am restructuring the code to make easier to create new devices. I also added a couple of new devices (ikea on/off button and xiaomi temperature sensors).
- I will update the wiki to explain how to add new devices soon

Regarding your fork:
- The only thing you are missing is the registration of the new device in [index.ts](https://github.com/manuchis/homebridge-zigbee-nt/blob/gledopto/src/index.ts#L74): in order to make the plugin support a new device you need to add the class definition to the internal registry. In your case, looking at the info returned by herdsman, you should register it like this:

> registerAccessoryClass('GLEDOPTO', ['GL-C-009'], GledoptoDim);

Of course you need to import the file as well.

- `updateDevice` function is not needed anymore, you can safely remove it. Now, every time the plugin receive a message from the Router, it first look if it should respond to a read request, then it decodes it using herdsman decoders and dispatch it using the new function [`update(device, state)`](https://github.com/madchicken/homebridge-zigbee-nt/blob/master/src/accessories/zig-bee-accessory.ts#L83), where state is a state update that will be automatically copied in the state properties of your device. Look [this part of the code](https://github.com/madchicken/homebridge-zigbee-nt/blob/master/src/platform.ts#L317) where I implemented this logic.

**Comment by manuchis** [comment]
Thanks, I believe I'm having issues making my changes work. I'm trying to install from github branch but it seems it is not installing properly. I will post updated when fixed

**Comment by madchicken** [comment]
There are many ways to test plugins, and you can find a lot of documentation out there, but my preferred way is to clone the repo In my home dir, build the plugin with `yarn build` and then create a link to the plugin folder from `/usr/local/lib/node_modules`. In this way, the plugin looks like it was installed from 6pm to homebridge, but you are able to change it and recompile as much as you want

**Comment by manuchis** [comment]
Great! it worked smoothly! 
many thanks.

**Comment by madchicken** [comment]
looking for a PR now 🙂
