### ISSUE TITLE
Question: Handling of attributes state

### ISSUE THREAD

**Issue by maccoylton** [madchicken/homebridge-zigbee-nt#213]
Hi,  I'm  trying to better understand how this library works. They way I thought this might would work would be when we establish a connection with an accessory, then we would query that accessory for all the relevant attributes, and then after that we get and push updates form/to the accessory periodically and/or when a value changes. 
 
That initial query doesn't seen to exist and therefore the state of attributes can be unknown for quite some time after start-up, for example in  thermostats valves it can be hours before we see the value of the current temperature is sent by the accessory and therefore known to homekit. 

Is my understanding correct?

**Comment by madchicken** [comment]
The way the device communicates with HK depends on the device itself: most of the devices notify the hub by periodically sending their status, since there is no way to read certain endpoints. The plugin is directly reading the endpoints when possible (and it does when HK requests it, for example when you ope the Home App on your phone), while it waits for an update where there is no READ endpoint.
For your specific case, it could be that we are missing to read a value even if we could retrieve to read it from the device.
I suggest you to look for your device into the Zigbee2MQTT website (https://www.zigbee2mqtt.io/supported-devices/) and check in the description what you can read and what you cannot.
An example is the TuYa TV02-Zigbee: take for example the Comfort temperature property, it says:
```
Value can be found in the published state on the comfort_temperature property. 
It's not possible to read (/get) this value. 
To write (/set) a value publish a message to topic zigbee2mqtt/FRIENDLY_NAME/set with payload {"comfort_temperature": NEW_VALUE}. 
The unit of this value is °C.
```

as you can see _It's not possible to read (/get) this value_

**Comment by maccoylton** [comment]
So on the devices types I'm focussed (TRV), it appears that the status message does not always contain all values where a get command is not possible, and instate they only become part of the state value as and when the accessory see it changing and then it send a status update.

In the case of a TVR this means the current_local_temperature and position are not always know when home bridge is started and it can take some time before those are updated, which isn't ideal, especially when debugging. 

it seems of the TRV you can "force" the current_local_temperature, as described below


If you'd like to force device to send local_temperature you can use this MQTT command:

    topic: zigbee2mqtt/FRIENDLY_NAME/set/local_temperature_calibration
    payload: YOUR_CURRENT_CALIBRATION_VALUE

YOUR_CURRENT_CALIBRATION_VALUE can be 0, but if you calibrated temperature for this device send current value. After this command thermostat responds with two messages. One for calibration change confirmation, and other with current local_temperature.
#

**Comment by madchicken** [comment]
@maccoylton sorry for the late reply to this. Yes, you are right about `current_local_temperature`, but by looking at the device definition in the herdsman library codebase I cannot find the converter needed for that operation:

https://github.com/Koenkk/zigbee-herdsman-converters/blob/v14.0.366/devices/tuya.js#L871-L877

All the logic to communicate with the device is done through converters defined into the that library. On the plugin side, all the "magic" is done here https://github.com/madchicken/homebridge-zigbee-nt/blob/master/src/zigbee/zig-bee-client.ts#L247-L259

In that code I try to fine the right converter by searching for keys in the `state` object. If the key is mapped in the converter, I map it. In this case, there is no converter mapping the key `local_temperature_calibration` for that device (if I am not wrong)

It could be either a documentation error or an error in the code. I'd open an issue there and see what they say about it
