### ISSUE TITLE
Xiaomi Button Suported Device WXKG01LM

### ISSUE THREAD

**Issue by wamfox** [madchicken/homebridge-zigbee-nt#68]
The [Xiaomi WXKG01LM](https://www.zigbee2mqtt.io/devices/WXKG01LM.html) works in the current version of the plugin and can be added to the supported device list in the wiki. Tho in my testing the long-press function does not seem to work tho the single and double press does so not sure if that should be fixed before it is added.

**Comment by madchicken** [comment]
Weird, I'll try to modify the action section for the button to see if I can fix this

**Comment by wamfox** [comment]
Thankyou I appreciate your time

**Comment by tr1ng0** [comment]
@madchicken 
Did you see that state.click is debrecated? This might be the issue here 
Quick question: why is it that sometimes modelID like WXKG01LM is a registerAccessoryClass and sometimes the zigbeeID and sometimes both. I do not get that 

You can asign me if you want I'll have a look, can't test it tho

**Comment by madchicken** [comment]
> Quick question: why is it that sometimes modelID like WXKG01LM is a registerAccessoryClass and sometimes the zigbeeID (lumi.sensor_switch) and sometimes both. I do not get that

Good catch: it really depends on the info the device is returning when it pairs. I had problems with my Philips Hue bulbs, that were using the zigbeeID, so I added them using it. We should probably use a better approach

**Comment by madchicken** [comment]
> @madchicken
> Did you see that state.click is debrecated? This might be the issue here
Good catch @tr1ng0. I'll change it in next unstable release (preparing it now...)

**Comment by tr1ng0** [comment]
Thanks! When checking the ikea-onoff-switch (because its the last class which implemented state.click) i saw that the zigbeeID is never used inside your code, this could resolve in bugs especially when overseeing somthing because the same device could be called twice just by modelID and zigbeeID ... I  just don't know what would be a better appoach tho

**Comment by madchicken** [comment]
I started to write some test a while ago, they are [here](https://github.com/madchicken/homebridge-zigbee-nt/blob/master/src/__tests__/registry.test.ts). We should add more entries in the DB (based on what we see in the reality) and check that we resolve the right device/model

**Comment by tr1ng0** [comment]
But what helps us achieve those tests? Sure before releasing something so tests are always good but you often handle theoratical zigbeeIDs and modelIDs you cant test because u dont own the device. Refactoring index.ts for better readabilty would be a start (sorting by model types and then add support for both zigbee and model ID?) to make sure nothing is missing? Just a suggestion

**Comment by tr1ng0** [comment]
Any updates @wamfox ? Is it resolved?
